# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highfives',
            field=models.ManyToManyField(related_name='myfives', to='login_a.User'),
        ),
    ]
